---

version: "3"

services:
  redis:
    image: redis
    restart: on-failure
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./.data/redis:/data

  search:
    image: getmeili/meilisearch
    volumes:
      - ./.data/ms:/data.ms
    ports:
      - 127.0.0.1:7700:7700
    environment:
      - MEILI_NO_ANALYTICS=yes
      - IN_DOCKER=yes

  proxy:
    build:
      dockerfile: ./Dockerfile.proxy
      context: .
    ports:
      - 127.0.0.1:8118:8118
      - 127.0.0.1:9050:9050
    environment:
      - TOR_NewCircuitPeriod=30
