---

version: "3"

services:
  parser:
    build:
      context: ./parser
    depends_on:
      - redis
      - search
    volumes:
      - ./.data/cache:/cache

  redis:
    image: redis
    restart: on-failure
    volumes:
      - ./.data/redis:/data

  search:
    image: getmeili/meilisearch
    volumes:
      - ./.data/ms:/data.ms
    ports:
      - 7700:7700
    environment:
      - MEILI_NO_ANALYTICS=yes
      - MEILI_MASTER_KEY=somerandomkey
      - IN_DOCKER=yes
